### ISSUE TITLE
More examples and strong documentation, please.

### ISSUE THREAD

**Issue by Illicitus** [python-gino/gino#376]
Hi, you did a great job and I say thank you. 

And like always I have only one wish for you, can you update your poor documentation and add more really difficult query request examples? For example we use GINO with PostGIS and create many difficult query with aggregation, annotation, pagination and it's really painful for us. We need to combine clear sqlalchemy query with Gino part, and it's not always work especially when we don't have strong documentation.  

Thanks.

**Comment by fantix** [comment]
Sorry for the trouble! Let me plan for a docs sprint within 0.8, so that it could reach production level when releasing 1.0 after 0.8.

Good to know that GINO's been used in heavy scenarios, it would be awesome if you could share some of your story - either successful or painful - with us, we are always looking forward to any chances to make improvements. My project at work using GINO was coming to an end, so it's becoming tougher for me to exercise GINO in practice, which makes your input more important.

**Comment by wwwjfy** [comment]
Before that happens, you can also check the documentation from SQLAlchemy about how to construct queries. Though gino doesn't have every feature, the basic select/join/where can be referenced.

**Comment by kodkuce** [comment]
Hmm i have a question i coudent find in tutorial i saw that "db.set_bind('postgresql://localhost/gino'" hmm that all cool and all but where do i set my username and pasword, i have a working SQLalchemy + flask that i am trying to port to aiohttp Gino, sorry duno if this i wrong place to ask :)

**Comment by fantix** [comment]
@kodkuce no worries, it's okay to ask here, or you can always create a new GitHub issue for questions.

The DSN string parsing logic is very much the same as it is in SQLAlchemy, so the auth info is similar too: `postgresql://username:password@localhost/gino`.

**Comment by fantix** [comment]
Closing this as we now have [more examples for Starlette/FastAPI](https://github.com/python-gino/gino-starlette/tree/master/examples) and [aiohttp](https://github.com/python-gino/gino-aiohttp/tree/master/examples). We'll track the documentation improvement in #146.
