### ISSUE TITLE
Session and Query

### ISSUE THREAD

**Issue by SantjagoCorkez** [python-gino/gino#478]
Is there any way to use SA's baked queries with Gino? According to documentation, baked queries require to use `sa.orm.Session` interface as Query object provider and that object as bakery accumulator. But Gino's Model.query provides `Executable` instead.

**Comment by wwwjfy** [comment]
While we can't use SA's baked query with Gino because Gino is not using SA's ORM (Query class), I think it's still possible to do similar optimisation by caching generated SQL statements.
But for now, it's not supported.

**Comment by myraygunbarrel** [comment]
So, there is no way to use relationship loading:

```python
session.query(Parent).options(
    joinedload(Parent.children).
    subqueryload(Child.subelements)).all()
```

with gino, because session object is required here. Am I right?

**Comment by fantix** [comment]
Right, GINO is built on SQLAlchemy core, not SQLAlchemy ORM.

**Comment by fantix** [comment]
> I think it's still possible to do similar optimisation by caching generated SQL statements.
Yes indeed! I'm thinking of adding a globally-named-prepared-statement feature in 1.1 - user would need to define their queries before the creation of database connection pool, and the first thing any new connection in the pool should do is to create the pre-configured named prepared statements so that at runtime any code could utilize these prepared statements to query the database without having to either parse the SQLAlchemy query or compile the SQL. I think this will significantly improve the issue mentioned in #631.

The motivation is that I wrote [rather complex queries](https://github.com/uc-cdis/fencex/blob/36c7c22b21d532805f361512563ceab6e441e47b/src/fencex/idps/ras/endpoint.py#L88-L156) in another project, and these queries won't change for different input values. It is a great fit to use prepared statements to boost performance.
