### ISSUE TITLE
Website is severely broken

### ISSUE THREAD

**Issue by retnikt** [python-gino/gino#664]
## Description

The python-gino.org website is severely broken when you resize the browser window. I thought you might like to know. Happens in both latest Firefox and Chrome. See screenshot.

![Screenshot_2020-05-03 python-gino org](https://user-images.githubusercontent.com/24581770/80918003-8966a500-8d5a-11ea-9bba-349269f62da8.png)

**Comment by retnikt** [comment]
Also this:
![image](https://user-images.githubusercontent.com/24581770/80918051-dba7c600-8d5a-11ea-80e0-3e829eb934bd.png)

![image](https://user-images.githubusercontent.com/24581770/80918060-e6625b00-8d5a-11ea-9abe-a52c280dac31.png)

**Comment by fantix** [comment]
Oh dear! Thanks for letting me know - I'll try to fix that.

**Comment by TomFaulkner** [comment]
I came here to report this as well. I am on an ultrawide 5k, but the browser window itself is only 1284px wide and I am getting similar very zoomed out issues. I was thinking maybe there was some JavaScript or something in the CSS that scaled depending on system resolution rather than window size.

This in Firefox.
![gino](https://user-images.githubusercontent.com/14956620/82125524-169ef600-976c-11ea-896c-46dd2bef077a.png)

**Comment by flapili** [comment]
Hi, the overflow-x on the breadcrumb is also broken on Opera and Edge, the responsive sidebar won't open either (the sidebar only containt hr).
![image](https://user-images.githubusercontent.com/29481952/82278161-d321d300-9989-11ea-9a58-21320f0fd790.png)
![image](https://user-images.githubusercontent.com/29481952/82278585-e08b8d00-998a-11ea-9822-9fc33cf37499.png)
I would like help you more but I don't master html or css a lot :/

**Comment by fantix** [comment]
Reporting is already super helpful! I don't have a lot of other devices but I'll try to fix as much as possible. Sorry for the inconvenience!

**Comment by fantix** [comment]
Now tracked in python-gino/python-gino.org#1 - didn't notice the "Issues" feature wasn't enabled for that repository. Thanks for all the reports!
